# docker-node: iris.haven
# port: 4100

# Service
apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  namespace: docker-ingress
spec:
  ports:
    - port: 80
      targetPort: 3210
---
# Endpoints
apiVersion: v1
kind: Endpoints
metadata:
  name: transmission-service
  namespace: docker-ingress
subsets:
  - addresses:
      - ip: 192.168.15.60
    ports:
      - port: 3210
---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-ingress
  namespace: docker-ingress
spec:
  rules:
    - host: transmission.haven
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission-service
                port:
                  number: 80
