---
# 1) Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homarr
  template:
    metadata:
      labels:
        app: homarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: SECRET_ENCRYPTION_KEY
              value: "c60b894215be5e4cc0fdd209aada8d83386b20579138ca143bc267c4c0042d08"
          ports:
            - containerPort: 7575
              name: homarr-port
          volumeMounts:
            - name: homarr-config
              mountPath: /appdata
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 250m
              memory: 1Gi
      volumes:
        - name: homarr-config
          persistentVolumeClaim:
            claimName: homarr-config
---
# 2) Service
apiVersion: v1
kind: Service
metadata:
  name: homarr
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: homarr
  ports:
    - port: 7575
      targetPort: homarr-port
---
# 3) PersistentVolumeClaim (for /config)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config
  namespace: default
  annotations:
    nfs.io/storage-path: "homarr-labs-config"
spec:
  storageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
# 4) Ingress (Traefik)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homarr
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: homarr.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homarr
                port:
                  number: 7575