apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: adguardhome-password, namespace: dns }
spec:
  refreshInterval: 1h
  target:
    name: adguardhome-password
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        { key: 5bc7e63f-18bb-482c-bc3e-740e03b26334, property: username }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
    - secretKey: password
      remoteRef:
        { key: 5bc7e63f-18bb-482c-bc3e-740e03b26334, property: password }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
