apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: archivebox-password, namespace: default }
spec:
  refreshInterval: 1h
  target:
    name: archivebox-password
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        { key: 6b4ca371-dcd4-4e31-aebe-8e5ea48b1fb9, property: username }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
    - secretKey: password
      remoteRef:
        { key: 6b4ca371-dcd4-4e31-aebe-8e5ea48b1fb9, property: password }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
