apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: cloudreve, namespace: cloud }
spec:
  refreshInterval: 1h
  target:
    name: cloudreve-secret
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        DB_USER: "{{ .DB_USER }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_NAME: "{{ .DB_NAME }}"
        REDIS_PASSWORD: "{{ .REDIS_PASSWORD }}"
  data:
    - secretKey: DB_USER
      remoteRef:
        { key: 8c25cac9-e9e8-4970-bdf4-31f9aee19276, property: username }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
    - secretKey: DB_PASSWORD
      remoteRef:
        { key: 8c25cac9-e9e8-4970-bdf4-31f9aee19276, property: password }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
    - secretKey: DB_NAME
      remoteRef:
        { key: 8c25cac9-e9e8-4970-bdf4-31f9aee19276, property: DB_NAME }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
    - secretKey: REDIS_PASSWORD
      remoteRef:
        { key: 8c25cac9-e9e8-4970-bdf4-31f9aee19276, property: REDIS_PASSWORD }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
