apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: discord-webhook, namespace: infra }
spec:
  refreshInterval: 1h
  target:
    name: discord-webhook
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        HAVEN_WEBHOOK_URL: "{{ .HAVEN_WEBHOOK_URL }}"
  data:
    - secretKey: HAVEN_WEBHOOK_URL
      remoteRef:
        {
          key: afd065bd-be8f-4e3c-a06e-e9d3089cb8f7,
          property: HAVEN_WEBHOOK_URL,
        }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
