apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: gitea-runner, namespace: dev }
spec:
  refreshInterval: 1h
  target:
    name: gitea-runner-token
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        REGISTRATION_TOKEN: "{{ .REGISTRATION_TOKEN }}"
  data:
    - secretKey: REGISTRATION_TOKEN
      remoteRef:
        {
          key: 4e286657-b5de-4354-be2e-d1649b0fd527,
          property: REGISTRATION_TOKEN,
        }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
