apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: recommender, namespace: media }
spec:
  refreshInterval: 1h
  target:
    name: recommender-secrets
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        OPENAI_API_KEY: "{{ .OPENAI_API_KEY }}"
        DATABASE_URL: "{{ .DATABASE_URL }}"
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        {
          key: 5079ef6f-3d1d-4522-b22c-6dd5f1c19acd,
          property: OPENAI_API_KEY,
        }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
    - secretKey: DATABASE_URL
      remoteRef:
        { key: 5079ef6f-3d1d-4522-b22c-6dd5f1c19acd, property: DATABASE_URL }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
