apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: renovate-bot, namespace: cronjobs }
spec:
  refreshInterval: 1h
  target:
    name: renovate-bot
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        RENOVATE_GITHUB_COM_TOKEN: "{{ .RENOVATE_GITHUB_COM_TOKEN }}"
        RENOVATE_TOKEN: "{{ .RENOVATE_TOKEN }}"
  data:
    - secretKey: RENOVATE_GITHUB_COM_TOKEN
      remoteRef:
        {
          key: 25b1f5c9-0a2b-438e-a4c6-23ea1d58e2de,
          property: RENOVATE_GITHUB_COM_TOKEN,
        }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        { key: 25b1f5c9-0a2b-438e-a4c6-23ea1d58e2de, property: RENOVATE_TOKEN }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
