apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: { name: slink, namespace: cloud }
spec:
  refreshInterval: 1h
  target:
    name: slink-secret
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        ADMIN_EMAIL: "{{ .ADMIN_EMAIL }}"
  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        { key: 79f97033-6bc3-40cd-a28c-6060b8bd3a63, property: username }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        { key: 79f97033-6bc3-40cd-a28c-6060b8bd3a63, property: password }
      sourceRef:
        { storeRef: { name: bitwarden-login, kind: ClusterSecretStore } }
    - secretKey: ADMIN_EMAIL
      remoteRef:
        { key: 79f97033-6bc3-40cd-a28c-6060b8bd3a63, property: ADMIN_EMAIL }
      sourceRef:
        { storeRef: { name: bitwarden-fields, kind: ClusterSecretStore } }
